name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
      - run: npm run check
      - run: npm run test
      - run: npm run test:e2e

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
      - run: npm run check
      - run: npm run test
      - run: npm run test:e2e
